[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GloGEM-documentation"
authors = [{name = "Janosch Beer", email = "beer@vaw.baug.ethz.ch"}]
dynamic = ["version", "description"]
